type: object
additionalProperties: false
properties:
  cluster: {$ref: "#/definitions/cluster"}

  tags:
    description: >
      Optional tags attached to your domain to make it easier to track and monitor.
    type: object
